import 'package:intl/intl.dart';

Map<String, dynamic> currentUser = {
  "username": "apollo",
  "email": "apollo@",
  "password": "aaaaaaaa",
  "discount": 0,
};
List<Map<String, dynamic>> orders = [];

List<Map<String, dynamic>> coubons = [
  {
    "code": "2314",
    "discount": 20,
  },
  {
    "code": "2114",
    "discount": 30,
  },
  {
    "code": "1114",
    "discount": 50,
  },
  {
    "code": "2333",
    "discount": 5,
  },
  {
    "code": "2364",
    "discount": 25,
  },
];
List<Map<String, dynamic>> accounts = [
  {
    "username": "apollo",
    "email": "apollo@",
    "password": "aaaaaaaa",
  },
  {
    "username": "Aren",
    "email": "aren@gmail.com",
    "password": "12121212",
  },
  {
    "username": "Hevar",
    "email": "hevar@gmail.com",
    "password": "12121212",
  },
  {
    "username": "Arkan",
    "email": "arkan@gmail.com",
    "password": "12121212",
  },
];

List<Map<String, dynamic>> basketItems = [];

List<Map<String, dynamic>> categories = [
  {
    "name": "Milk",
    "imgPath": "assets/categories/milk.png",
    "discount": 20,
    "isTop": false,
  },
  {
    "name": "Coffee",
    "imgPath": "assets/categories/coffee.png",
    "discount": 30,
    "isTop": false,
  },
  {
    "name": "Meat",
    "imgPath": "assets/categories/meat.png",
    "discount": 20,
    "isTop": true,
  },
  {
    "name": "Drinks",
    "imgPath": "assets/categories/drinks.png",
    "discount": 20,
    "isTop": false,
  },
  {
    "name": "Fruits",
    "imgPath": "assets/categories/fruits.png",
    "discount": 15,
    "isTop": true,
  },
  {
    "name": "Greens",
    "imgPath": "assets/categories/greens.png",
    "discount": 20,
    "isTop": true,
  },
  {
    "name": "Snacks",
    "imgPath": "assets/categories/snacks.png",
    "discount": 10,
    "isTop": true,
  },
  {
    "name": "Protein",
    "imgPath": "assets/categories/protein.png",
    "discount": 25,
    "isTop": false,
  },
  {
    "name": "Bread",
    "imgPath": "assets/categories/bread.png",
    "discount": 15,
    "isTop": false,
  },
  {
    "name": "Seafood",
    "imgPath": "assets/categories/seafood.png",
    "discount": 18,
    "isTop": false,
  },
];

List<Map<String, dynamic>> products = [
  {
    "name": "Watermelon",
    "imgPath": "assets/products/watermelon.png",
    "details": "Food Details",
    "price": 1500,
    "category": "Fruits",
    "quantity": 1,
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Chips",
    "imgPath": "assets/products/chips.png",
    "details": "Food Details",
    "price": 1500,
    "category": "Snacks",
    "quantity": 1,
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Coffee",
    "imgPath": "assets/products/coffee.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Coffee",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Milk",
    "imgPath": "assets/products/milk.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Milk",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Neutonic",
    "imgPath": "assets/products/neutonic.png",
    "details": "Food Details",
    "price": 1500,
    "category": "Drinks",
    "quantity": 1,
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Pepsi",
    "imgPath": "assets/products/pepsi.png",
    "details": "Food Details",
    "price": 1500,
    "category": "Drinks",
    "quantity": 1,
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Redbull",
    "imgPath": "assets/products/redbull.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Drinks",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Kinder",
    "imgPath": "assets/products/kinder.png",
    "details": "Snack Details",
    "price": 1500,
    "quantity": 1,
    "category": "Snacks",
    "isTrending": false,
    "totalPrice": 1500,
  },
  {
    "name": "Banana",
    "imgPath": "assets/products/banana.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Fruits",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Broccoli",
    "imgPath": "assets/products/broccoli.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Greens",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Lemon",
    "imgPath": "assets/products/lemon.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Fruits",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Orange",
    "imgPath": "assets/products/orange.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Fruits",
    "isTrending": true,
    "totalPrice": 1500,
  },
  {
    "name": "Yogurt",
    "imgPath": "assets/products/yogurt.png",
    "details": "Beverage Details",
    "price": 1500,
    "quantity": 1,
    "category": "Milk",
    "isTrending": false,
    "totalPrice": 1500,
  },
  {
    "name": "Salmon",
    "imgPath": "assets/products/salmon.png",
    "details": "Seafood Details",
    "price": 1500,
    "quantity": 1,
    "category": "Seafood",
    "isTrending": false,
    "totalPrice": 1500,
  },
  {
    "name": "Apple",
    "imgPath": "assets/products/apple.png",
    "details": "Food Details",
    "price": 1500,
    "quantity": 1,
    "category": "Fruits",
    "isTrending": false,
    "totalPrice": 1500,
  },
];
